timetracker/myapp/urls.py
from django.conf.urls import url

from .views import IndexView, RestrictedView, MonthView, DayView

app_name = 'myapp'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^restricted$', RestrictedView.as_view(), name='restricted'),
    url(r'^(?P<year>\d{4})/$', MonthView.as_view(), name='year'),
    url(r'^(?P<year>\d{4})/(?P<month>\w{3})/$', MonthView.as_view(),
        name='month'),
    url(r'^(?P<year>\d{4})/(?P<month>\w{3})/'
        r'(?P<day>([1-9]|0[1-9]|[12][0-9]|3[01]))$',
        DayView.as_view(), name='day'),
]

timetracker/timetracker/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url('^', include('django.contrib.auth.urls')),
    url(r'^other/', include('myapp.urls', namespace='myapp')),
    url(r'^tracker/', include('tracker.urls')),
    url(r'^admin/', admin.site.urls),
]

timetracker/myapp/models.py
from django.db import models
from django.contrib.auth.models import User


class UserData(models.Model):
    user = models.ForeignKey(User, editable=False)

    class Meta:
        abstract = True


class Entry(UserData):
    date = models.DateField('date')
    start = models.TimeField('start time')
    stop = models.TimeField('stop time')
    task = models.CharField('task', max_length=200)

    def __str__(self):
        return "<Entry: ({} {}-{}) {}>".format([self.date, self.start,
                                                self.stop, self.task])

timetracker/myapp/forms.py
from django import forms

from .models import Entry


class TaskEntryForm(forms.ModelForm):
    start = forms.TimeInput(format='%H:%M')
    stop = forms.TimeInput(format='%H:%M')
    task = forms.CharField(max_length=200)

    class Meta:
        model = Entry
        fields = ['start', 'stop', 'task']

timetracker/myapp/views.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect

from .forms import TaskEntryForm
from .models import Entry

import datetime
import calendar
from dateutil.parser import parse
from dateutil.relativedelta import relativedelta as delta

calendar.setfirstweekday(calendar.MONDAY)


def _months(arg=None):
    months = [('', ''), ('January', 'Jan'), ('February', 'Feb'),
              ('March', 'Mar'), ('April', 'Apr'), ('May', 'May'),
              ('June', 'Jun'), ('July', 'Jul'), ('August', 'Aug'),
              ('September', 'Sep'), ('October', 'Oct'), ('November', 'Nov'),
              ('December', 'Dec')]
    if arg:
        if arg.isdigit():
            return months[int(arg)]
        else:
            arg = arg.capitalize()
            if len(arg) == 3:
                try:
                    idx = [i for i, v in enumerate(months) if v[1] == arg][0]
                except IndexError:
                    return None
            else:
                try:
                    idx = [i for i, v in enumerate(months) if v[0] == arg][0]
                except IndexError:
                    return None
        return idx
    return months


class IndexView(generic.base.TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        return context


class RestrictedView(LoginRequiredMixin, generic.base.TemplateView):
    template_name = 'restricted.html'

    def get_context_data(self, **kwargs):
        context = super(RestrictedView, self).get_context_data(**kwargs)

        return context


class MonthView(generic.base.TemplateView):
    template_name = 'month.html'

    def get_context_data(self, **kwargs):
        context = super(MonthView, self).get_context_data(**kwargs)
        context['today'] = datetime.date.today().strftime('%Y-%b-%d').split('-')
        context['month'] = context.get('month', context['today'][1])
        context['months'] = _months()[1:]
        context['daynames'] = calendar.weekheader(2).split(" ")
        context['days'] = calendar.monthcalendar(int(context['year']),
                                                 _months(context['month']))
        context['prev_year'] = int(context['year']) - 1
        context['next_year'] = int(context['year']) + 1

        view_date = '-'.join([context['year'], context['month']])
        prev_month = (parse(view_date) + delta(months=-1)).strftime('%Y/%b')
        next_month = (parse(view_date) + delta(months=+1)).strftime('%Y/%b')
        context['prev_month'] = prev_month.split('/')
        context['prev_month_s'] = prev_month
        context['next_month'] = next_month.split('/')
        context['next_month_s'] = next_month
        return context


class DayView(generic.list.ListView):
    model = Entry
    context_object_name = 'entries'
    template_name = 'day.html'
    object_list = None
    view_date = ''

    def get_queryset(self):
        queryset = super(DayView, self).get_queryset()
        self.view_date = '-'.join([self.kwargs['year'],
                                   str(_months(self.kwargs['month'])),
                                   self.kwargs['day']])
        return queryset.filter(date=self.view_date).order_by('start')

    def get_context_data(self, **kwargs):
        context = super(DayView, self).get_context_data(**kwargs)
        context['form'] = TaskEntryForm

        prev_day = (parse(self.view_date) + delta(days=-1)).strftime('%Y/%b/%d')
        next_day = (parse(self.view_date) + delta(days=+1)).strftime('%Y/%b/%d')
        context['prev_day'] = prev_day.split('/')
        context['prev_day_s'] = prev_day
        context['next_day'] = next_day.split('/')
        context['next_day_s'] = next_day
        return context

    def post(self, request, *args, **kwargs):
        form = TaskEntryForm(request.POST)
        self.object_list = self.get_queryset()

        if 'add' in request.POST:
            if form.is_valid():
                context = self.get_context_data(**kwargs)
                context['form'] = TaskEntryForm
                form_data = form.save(commit=False)
                form_data.date = parse(self.view_date)
                form_data.user = self.request.user
                form_data.save()
                return redirect(request.META['HTTP_REFERER'])
            else:
                context = self.get_context_data(**kwargs)
                context['form'] = form
        elif 'delete' in request.POST:
            context = self.get_context_data(**kwargs)

            entry_id = request.POST.get('delete')
            query = Entry.objects.get(pk=entry_id).delete()
        else:
            context = self.get_context_data(**kwargs)

        return self.render_to_response(context=context)

timetracker/myapp/templates/day.html
{% extends "base.html" %}

{% block content %}

<div class="panel panel-default">
    <div class="panel-body">
        <button><a href="{% url 'myapp:day' prev_day.0 prev_day.1 prev_day.2 %}">{{ prev_day_s }}</a></button>
        <button><a href="{% url 'myapp:day' next_day.0 next_day.1 next_day.2 %}">{{ next_day_s }}</a></button>
    </div>
</div>

<form method="POST" >
  {% csrf_token %}

  {{ form.as_ul }}


  <button type="submit" name="add" class="btn btn-xs btn-danger pull-right" >
    <span class="glyphicon glyphicon-remove" ></span >
  </button >
</form >


<div class="row" >
  <table class="table table-striped" >
    <thead >
    <tr >
      <th class="col-xs-2" ></th >
      <th class="col-xs-2" ></th >
      <th class="col-xs-6" ></th >
      <th class="col-xs-1" ></th >
    </tr >
    </thead >

    <tbody >
    {% for entry in object_list %}
    <tr >
      <td >{{ entry.start|date:'H:i' }} - {{ entry.stop|date:'H:i' }}</td >
      <td >{{ entry.task }}</td >
      <td >
        <form method="POST" >{% csrf_token %}
          <button type="submit" name="delete" id="delete" value="{{ entry.id }}"
                  class="btn btn-xs btn-danger pull-right" >
            <span class="glyphicon glyphicon-remove" ></span >
          </button >
        </form >
      </td >
    </tr >
    {% endfor %}
    </tbody >
  </table >
</div >


{% endblock %}

timetracker/myapp/templates/index.html
{% extends "base.html" %}

{% block content %}

~ My App ~

{% endblock %}

timetracker/myapp/templates/month.html
{% extends "base.html" %}

{% block content %}

<div class="panel panel-default">
    <div class="panel-body">
        <button><a href="{% url 'myapp:year' prev_year %}">{{ prev_year }}</a></button>
        <ul class="nav nav-pills">
            {% for monthname in months %}
            {% ifequal monthname.1 month %}
            <li role="presentation" class="active"><a href="{% url 'myapp:month' year monthname.1 %}">{{ monthname.0 }}</a></li>
            {% else %}
            <li role="presentation"><a href="{% url 'myapp:month' year monthname.1 %}">{{ monthname.0 }}</a></li>
            {% endifequal %}
            {% endfor %}
        </ul>
        <button><a href="{% url 'myapp:year' next_year %}">{{ next_year }}</a></button>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <button><a href="{% url 'myapp:month' prev_month.0 prev_month.1 %}">{{ prev_month_s }}</a></button>
        <h2 class="panel-title text-center">{{ month }} {{ year }}</h2>
        <button><a href="{% url 'myapp:month' next_month.0 next_month.1 %}">{{ next_month_s }}</a></button>
    </div>
    <table class="table">
        <thead class="">
        <tr>
            {% for day in daynames %}
            <th class="text-center">{{ day }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for week in days %}
        <tr>
            {% for day in week %}
            {% if day != 0 %}
            {% ifequal year|stringformat:"s" today.0 %}
            {% ifequal month today.1 %}
            {% ifequal day|stringformat:"s" today.2 %}
            <td class="text-center info">
                {% else %}
            <td class="text-center">
                {% endifequal %}
                {% else %}
            <td class="text-center">
                {% endifequal %}
                {% else %}
            <td class="text-center">
                {% endifequal %}
                <a href="{% url 'myapp:month' year month %}{{ day }}">{{ day }}</a>
            </td>
            {% else %}
            <td class="text-center"></td>
            {% endif %}
            {% endfor %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

timetracker/myapp/templates/restricted.html
{% extends "base.html" %}

{% block content %}

Not for public consumption

{% endblock %}